default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trackstack_development

test:
  <<: *default
  database: trackstack_test

production:
  <<: *default
  database: trackstack_production
  username: trackstack
  password: <%= ENV['TRACKSTACK_DATABASE_PASSWORD'] %>
